### ISSUE TITLE
Allow user to enter IP manually

### ISSUE THREAD

**Issue by TheAssassin** [Hypfer/valetudo-companion#10]
Since some of my "IoT" stuff is in a separated subnet and passes a router, zeroconf with UDP broadcasts doesn't really work. I'd need to enter the IP manually to use this app. I think it could be integrated as some sort of "advanced" option.

**Comment by TheLastProject** [comment]
If you have to enter your IP manually, why use the app? Given all the app does is open the web-UI in your browser? You may just as well type the IP directly into your browser then, exact same functionality.

**Comment by TheAssassin** [comment]
Well, I haven't tried the app, really, because of said issue. In that case, feel free to close the issue. I was expecting some sort of sophisticated UI using some API or something like that. Now I also found the corresponding snippet in the README:

> This app will not provide any UI to interface with Valetudo during normal operation. Basically, you can think of it as an automatically updating bookmark + some wizard stuff.

**Comment by TheLastProject** [comment]
Nah, no need to recreate the UI :)

The provisioning does use the API, but that involves connecting to the robot's network anyway so your network separation shouldn't be relevant then.

**Comment by TheAssassin** [comment]
Indeed. Given the purpose of this companion app, I don't think I'll ever need it for my purposes.
