### ISSUE TITLE
Crash if no browser is installed to handle the `browserIntent`

### ISSUE THREAD

**Issue by JayFoxRox** [Hypfer/valetudo-companion#11]
Valetudo Companion will crash here if no browser (or other app) is present to handle `http:`:

https://github.com/Hypfer/valetudo-companion/blob/f745b08ae29c91f549355aab8335568561934286/app/src/main/java/cloud/valetudo/companion/MainActivity.kt#L57-L62

---

I assume it will require something like this: https://developer.android.com/training/basics/intents/sending#no-app-available

There should probably be a descriptive error and a copyable-URL should be shown for manual use.

**Comment by Hypfer** [comment]
Might be fixed by 759e93c383359f21868f352c063f53ac0dafc0ae

**Comment by Hypfer** [comment]
I was able to verify this in an emulator
