### ISSUE TITLE
SDK 33: New runtime permission for nearby Wi-Fi devices

### ISSUE THREAD

**Issue by TheLastProject** [Hypfer/valetudo-companion#15]
Valetudo Companion currently targets SDK level 30 (Android 11).

SDK level 33 (Android 13) introduces new permissions for scanning for Wi-Fi access points: [NEARBY_WIFI_DEVICES](https://developer.android.com/reference/android/Manifest.permission#NEARBY_WIFI_DEVICES). [ACCESS_FINE_LOCATION](https://developer.android.com/reference/android/Manifest.permission#ACCESS_FINE_LOCATION) is no longer necessary. See https://developer.android.com/about/versions/13/behavior-changes-13#nearby-wifi-devices-permission for more info.

Preferably, updating the targetSdk should be done before November 2022 so that releasing updates onto Google Play isn't blocked. It should definitely be done before November 2023 so the app doesn't disappear from Google Play: https://support.google.com/googleplay/android-developer/answer/11926878

**Comment by Hypfer** [comment]
93716257cc4ebf43cac59acce50331498a9a4b32
