### ISSUE TITLE
Add option to manually specify robot's IP address.

### ISSUE THREAD

**Issue by AndrisJrs** [Hypfer/valetudo-companion#19]
As I have robot that is on separate IoT subnet from my phone and Bonjour broadcasts aren't passed between subnets. I would like to have an option to manually specify robot's IP address/domain to access robot through valetudo-companion.

**Comment by Hypfer** [comment]
If you know the IP of the robot, you don't need this app.

Keep in mind that the companion app does not provide any UI whatsoever. Tapping on an instance will only open the WebInterface in a Browser Window. If you already know the IP, the same can be achieved by putting a bookmark to that IP on your homescreen
